### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-misc#12]
# Story

As a developer, in order to DO ALL THE THINGS, I need the project to be setup

# Acceptance Criteria

**When** the developer clones the repo
**Then** they should have all the files they need

**Comment by daviddassau** [comment]
**Directories and files:**

- db
	- apiKeys.example.json
	- apiKeys.json
	- theme-park.json
- dist (to be created once grunt is running)
- javascripts
	- main.js
	- events.js
	- dom.js
	- firebaseApi.js
- lib
	- Gruntfile.js

- sass
	- _colors
- index.html
- .gitignore
- README.md

**Comment by alexsanchez728** [comment]
data.js :

areaPromise,
attractionPromise,
attratcitonTypePromise,
parkInfoPromise,

name: callData
Parameters: none
what it does: calls area, attraction, attraction type promises, calls combine data function

name: combineData
Parameters: areaData, attractionData, attractionTypeData
wat itdo: combine all data to create parkMash array & sets the array as a global variable

name: getParkMash
Parameters: none
waht it duz: returns parkMash array

**Comment by alexsanchez728** [comment]
firebaseApi.js:

hold our key and Uid,
Authenticate function
