### ISSUE TITLE
Areas should be displayed in rectangular grid

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-misc#2]
# Story

As a user, in order to see where areas are located, I need to see the park laid out in a grid

# Acceptance Criteria

**Given** the area data has been loaded
**When** the application renders
**Then** the areas should be represented to the user as a 3-3-2 grid, with the middle cell of the last row unoccupied, and each area colored with its corresponding hex value (i.e. the `colorGrid` value)

<table>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>3</td>
  </tr>
  <tr>
    <td>4</td>
    <td>5</td>
    <td>6</td>
  </tr>
  <tr>
    <td>7</td>
    <td></td>
    <td>8</td>
  </tr>
</table>

**Comment by daviddassau** [comment]
**Rough outline of static code in index.html**

```
<div class="container">
	<div class="row">
		<!-- 30 percent sidebar -->
		<div class="col-sm-4">

		</div>
		<!-- 3 x 3 x 2 layout -->
		<div class="col-sm-4">

		</div>
	</div>
</div>
```

There are only 7 "areas" in the JSON file, and 8 boxes shown above, so in the 3rd row we're going to have only 1 box to the far right.

**Comment by daviddassau** [comment]
The 7 cards, representing each "area" of the park, will be displayed dynamically on the page, using a `printToDom` function.

**Comment by alexsanchez728** [comment]
![imag0321 1](https://user-images.githubusercontent.com/30006994/32200471-cb23b09c-bd9f-11e7-809d-acf78b70378d.jpg)

**Comment by GinaAntonini** [comment]
Set hex values as colors in _colors.scss

**Comment by GinaAntonini** [comment]
Data Structure: 
![img_4567](https://user-images.githubusercontent.com/30006992/32202484-19966002-bdab-11e7-869f-78994d693d6a.JPG)
