### ISSUE TITLE
User should be able to see all attractions in an area - domString function 

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-misc#3]
This item is for the domString function to write the attractions data to the left pane

# Story

As a user, in order to explore attractions near me, I need to highlight an area of the park and see all attractions in it

# Acceptance Criteria

**Given** user wants to see the attraction list of an area
**When** the user clicks on an area
**Then** all attraction names assigned to that area should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

**Comment by alexsanchez728** [comment]
![imag0321](https://user-images.githubusercontent.com/30006994/32137263-2260c4cc-bbe2-11e7-8e8b-0451e1ff0b9e.jpg)

**Comment by GinaAntonini** [comment]
In index.html:
Create div with id of "areas" 
Create div with id of "sidebar"

**Comment by gib-bowden** [comment]
Reopening - we still need to wire this up

**Comment by gib-bowden** [comment]
created new issue #26 to handle the click event - closing this one
